config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'share' => 'decks#share'

  #Decks > cards
  resources :decks do
    member do
      resources :cards
    end
  end

end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :deck
	validates :front, :back, presence: true

	#Checks if cards has more entry/deck
	def next
	  self.class.where("deck_id == ?", deck_id).where("id > ?", id).first
	end

	def previous
	  self.class.where("deck_id == ?", deck_id).where("id < ?", id).last
	end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, uniqueness: {scope: :user_id}, length: {maximum: 30}
  validates :user_id, presence: true
  before_create :set_last_visited_to_now
  has_many :cards, dependent: :destroy

  def set_last_visited_to_now
  	self.last_visited = DateTime.now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :decks, dependent: :destroy
  validates :username, presence: true, uniqueness: true, length: {maximum: 30}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  #Requires login
  def require_login
  	unless signed_in?
  		flash[:error] = "Please login to view content"
  		redirect_to root_path
  	end
  end

  #Devise override to redirect after signing in
  def after_sign_in_path_for(resource)
    decks_path
  end

  #Devise permit username variable
  protected

  def configure_devise_permitted_parameters
    registration_params = [:username, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_action :require_login

	def new
		@card = Deck.find(params[:id]).cards.build
	end

	def show
		@card = Card.find(params[:id])
		@deck = Deck.find_by(@card.deck_id)
	end

	def create
		@card = Deck.find(params[:id]).cards.build(card_params)
		if @card.save
			flash[:success]  = "Card successfully added"
			redirect_to deck_path(@card.deck_id)
		else
			flash[:error]  = "Error creating card"
			redirect_to deck_path(@card.deck_id)
		end
	end

	def edit
		@card = Card.find(params[:id])
		if @card.update(card_params)
			flash[:success]  = "Card successfully edited"
			redirect_to deck_path(@card.deck_id)
		else
			flash[:error]  = "Error editing card"
			redirect_to deck_path(@card.deck_id)
		end

	end

	def destroy
		@card = Card.find(params[:id])
		@id = @card.deck_id
		@card.destroy
		redirect_to(deck_path(@id))
	end

	private

	def card_params
		params.require(:card).permit(:front,:back)
	end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
	before_action :require_login
	before_action :last_visited, only: [:show]
	before_action :correct_user, only: [:show]
	before_action :creator?, only: [:edit, :delete]

	def new
		@deck = current_user.decks.build
	end

	def index
		@decks = current_user.decks.order(last_visited: :desc)
		@deck = current_user.decks.build
	end

	def create
		@deck = current_user.decks.build(deck_params)
		if @deck.save
			flash[:success] = 'Deck successfully created'
			redirect_to decks_path
		else
			flash[:error] = "Error creating deck"
			redirect_to decks_path
		end
	end

	def share
		@decks = Deck.where(share: true)
	end

	def show
		@deck = Deck.find(params[:id])
		@cards = @deck.cards
		@card = Deck.find(params[:id]).cards.build()
	end

	def edit
		@deck = Deck.find(params[:id])
		@deck.update(deck_params)
		redirect_to decks_path
	end

	def update
		@deck = Deck.find(params[:id])
		@deck.update(deck_params)
		redirect_to decks_path
	end

	def destroy
		@deck = Deck.find(params[:id])
		@deck.destroy
		flash[:success] = "Deck successfully deleted"
		redirect_to decks_path
	end

	private

	def deck_params
		params.require(:deck).permit(:title, :share)
	end

	#Updates the last visited
	def last_visited
	  Deck.find(params[:id]).update_attribute(:last_visited, DateTime.now)
	end

	#Checks if the owner of the deck is visiting or it is shared
	def correct_user
		unless current_user.id == Deck.find(params[:id]).user_id or Deck.find(params[:id]).share == true
			flash[:error] = "You do not have permission to look at this deck"
			redirect_to root_path
		end
	end

	#Checks if the current user is the creator of the deck
	def creator?
		unless current_user.id == Deck.find(params[:id]).user_id
			flash[:error] =  "You do not have permission to modify this deck"
			redirect_to root_path
		end
	end
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end

  def about

  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
	  case flash_type
	  when "success"
	    "alert-success"   # Green
	  when "error"
	    "alert-danger"    # Red
	  when "alert"
	    "alert-warning"   # Yellow
	  when "notice"
	    "alert-info"      # Blue
	  else
	    flash_type.to_s
	  end
	end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
	def deck_creator?
		current_user.id == @deck.user_id
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/show.html.erb
<div class="container">
	<div class="row row-header">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<p style="padding-bottom:5%;"></p>
		</div>
	</div>

	<div class="row row-content">
		<div class="col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="btn-group col-md-12 col-sm-12 col-xs-12" style="margin-top:20px;">
					<h2 class="pull-left">Card</h2>
					<div class="btn-group pull-right" style="margin-top:20px;">
						<%= link_to "Edit Card", '#', class: 'btn-info btn btn-sm', type:"button", 'data-toggle' => "modal", 'data-target' => "#cardModal" %>
						<%= link_to "Delete Card", '#', class: 'btn-danger btn btn-sm', type:"button", 'data-toggle' => "modal", 'data-target' => "#deleteDeck" %>
					</div>

				</div>
			</div>
			<div class="col-md-12 col-sm-12 col-xs-12">
				<hr>
				<div class="col-md-12 col-sm-12 col-sm-12">
					<p style="padding-top:5px;"></p>
					<div class="deck-content col-md-12 col-xs-12 col-sm-12">
						<div class="front-card">
							<div class="text-center">
								<h3 class="front"><%= @card.front %></h3>
							</div>
						</div>
						<hr>
						<div class="back-card">
							<div class="text-center">
								<h3 class="back"><%= @card.back %></h3>
							</div>
						</div>
						<br>
						<button class="btn btn-block btn-info" id="show">Show card</button>
						<p style="padding-top: 20px;"></p>
					</div>
				</div>
			</div>
			<footer class="text-center">
			  <%= link_to "Return", deck_path(@card.deck_id), class:"btn btn-default" %>
			</footer>
		</div>
		<% unless @card.previous.nil? %>
		<div class="arrowleft">
			<%= link_to card_path(@card.previous) do %><span class="glyphicon glyphicon-arrow-left"></span><% end %>
		</div>
		<% end %>
		<% unless @card.next.nil? %>
		<div class="arrowright">
			<%= link_to card_path(@card.next) do %><span class="glyphicon glyphicon-arrow-right"></span><% end %>
		</div>
		<% end %>
	</div>
</div>

<!-- Edit Card Modal -->
<% provide :cardPurpose,'Edit Card' %>
<% provide :cardSubmit,'Edit'  %>
<%= render 'shared/cardModal' %>


<!-- Delete Card Modal -->
<% provide :delete_id, "deleteCard" %>
<% provide :delete_path, card_path(@card) %>
<%= render 'shared/deletecontent' %>

<script>
//Hides back and shows when clicked on and disables button
$(document).ready(function(){
	$(".back").hide();
    $("#show").click(function(){
        if(!$('#show').hasClass('disabled')){
        	$(".back").show();
        	$('#show').toggleClass('disabled');
        }
    });
});
</script>

app/views/decks/_new_deck.erb
<!-- New Deck Modal -->
<div id="newDeck" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= yield :modal_title %></h4>
      </div>
      <div class="modal-body">
		<%= form_for @deck do |f| %>
			<div class="form-group">
				<%= f.label :Name %><em>(Maximum 30 characters)</em></p>
				<%= f.text_field :title, class:"form-control", placeholder: 'Title of the Deck', required: true %>
			</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <%= f.submit yield(:modal_submit), class: "btn btn-success pull-right" %>
      </div>
		<% end %>
    </div>

  </div>
</div>

app/views/decks/index.html.erb
<div class="container">
	<div class="row row-header">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<p style="padding-bottom:5%;"></p>
		</div>
	</div>

	<div class="row row-content">
		<div class="col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<h2 class="pull-left">Decks</h2>
				<%= link_to "Create New Deck", '#', class: 'pull-right btn-success btn', style: 'margin-top:20px;', type:"button", 'data-toggle' => "modal", 'data-target' => "#newDeck" %>
			</div>
			<div class="col-md-12 col-sm-12 col-xs-12">
				<hr>
				<% if @decks.length != 0 %>
					<div class="col-md-12 col-sm-12 col-sm-12">
						<div class="deck-header col-md-12 col-xs-12 col-sm-12">
							<p class="col-md-7 col-sm-2 col-xs-3"><strong>Name</strong></p>
							<p class="col-md-2 col-sm-2 col-xs-4 text-center"><strong># Cards</strong></p>
							<p class="col-md-3 col-sm-8 col-xs-5"><strong>Last viewed</strong></p>
						</div>
						<% @decks.each do |f| %>
							<% unless f.id.nil? %>
							<div class="decks col-md-12 col-xs-12 col-sm-12">
							<p style="padding-top:5px;"></p>
							<%= link_to truncate(f.title, length: 70), deck_path(f.id), class:'col-md-7 col-sm-2 col-xs-3' %>
							<%= link_to f.cards.length, deck_path(f.id), class:"col-md-2 col-sm-2 col-xs-4 text-center" %>
							<%= link_to f.last_visited.strftime("%m/%d/%Y, %I:%M %Z"), deck_path(f.id), class: 'col-md-3 col-sm-8 col-xs-5' %>
							</div>
							<% end %>
						<% end %>
					</div>
				<% else %>
					<p>The birds are chirping, why don't you create some decks to get started!</p>
				<% end %>
			</div>
		</div>
	</div>
</div>

<% provide :modal_title, 'Create New Deck' %>
<% provide :modal_submit, "Edit" %>
<%= render 'new_deck' %>

app/views/decks/share.html.erb
<div class="container">
	<div class="row row-header">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<p style="padding-bottom:5%;"></p>
		</div>
	</div>

	<div class="row row-content">
		<div class="col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<h2 class="pull-left">Shared Decks</h2>
			</div>
			<div class="col-md-12 col-sm-12 col-xs-12">
				<hr>
				<% if @decks.length != 0 %>
					<div class="col-md-12 col-sm-12 col-sm-12">
						<div class="deck-header col-md-12 col-xs-12 col-sm-12">
							<p class="col-md-4 col-sm-2 col-xs-3"><strong>Name</strong></p>
							<p class="col-md-2 col-sm-2 col-xs-4 text-center"><strong># Cards</strong></p>
							<p class="col-md-3 col-sm-2 col-xs-4 text-center"><strong>Last updated</strong></p>
							<p class="col-md-3 col-sm-8 col-xs-5"><strong>Creator</strong></p>
						</div>
						<% @decks.each do |f| %>
							<% unless f.id.nil? %>
							<div class="decks col-md-12 col-xs-12 col-sm-12">
								<p style="padding-top:5px;"></p>
								<%= link_to truncate(f.title, length: 50), deck_path(f.id), class:'col-md-4 col-sm-2 col-xs-3' %>
								<p class="col-md-2 col-sm-2 col-xs-4 text-center"><%= f.cards.length %></p>
								<p class="col-md-3 col-sm-2 col-xs-4 text-center"><%= f.updated_at.strftime("%m/%d/%Y, %I:%M %Z") %></p>
								<p class="col-md-3 col-sm-8 col-xs-5"><%= truncate(User.find(f.user_id).username,length:30) %></p>
							</div>
							<% end %>
						<% end %>
					</div>
				<% else %>
					<p>No decks are being shared right now</p>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/decks/show.html.erb
<!-- Return link to decks -->
<% provide :return_link, decks_path%>


<div class="container">
	<div class="row row-header">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<p style="padding-bottom:5%;"></p>
		</div>
	</div>

	<div class="row row-content">
		<div class="col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<h2 class="pull-left"><%= truncate(@deck.title, length: 20) %></h2>
				<div class="btn-group pull-right visible-lg visible-md" style="margin-top:20px;">
					<% if @deck.share == false %>
					<%= link_to "Share Deck", '#', class: 'btn-warning btn btn-sm', type:"button", 'data-toggle' => "modal", 'data-target' => "#shareDeck" %>
					<% else %>
					<% if deck_creator? %>
					<%= link_to '#', class: 'btn-success btn btn-sm disabled' do %><span class="glyphicon glyphicon-check"></span>Already sharing<% end %>
					<% end %>
					<% end %>
					<% if deck_creator? %>
					<%= link_to "Delete Deck", '#', class: 'btn-danger btn btn-sm', type:"button", 'data-toggle' => "modal", 'data-target' => "#deleteDeck" %>
					<%= link_to "Edit Deck", '#', class: 'btn-info btn btn-sm', type:"button", 'data-toggle' => "modal", 'data-target' => "#newDeck" %>
					<% end %>
					<%= link_to "Create New Card", '#', class: 'btn-success btn btn-sm', type:"button", 'data-toggle' => "modal", 'data-target' => "#cardModal" %>
				</div>
				<div class="dropdown visible-xs visible-sm col-sm-12 col-xs-12">
				  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Options
				  <span class="caret"></span></button>
				  <ul class="dropdown-menu">
				    <% if @deck.share == false %>
				    <li><%= link_to "Share Deck", '#', type:"button", 'data-toggle' => "modal", 'data-target' => "#shareDeck" %></li>
				    <% else %>
					<li><%= link_to '#' do%><span class="glyphicon glyphicon-check"></span>Already sharing<% end %></li>
				    <% end %>
				    <li><%= link_to "Delete Deck", '#', type:"button", 'data-toggle' => "modal", 'data-target' => "#deleteDeck" %></li>
				    <li><%= link_to "Edit Deck", '#', type:"button", 'data-toggle' => "modal", 'data-target' => "#newDeck" %></li>
				    <li class="divider"></li>
				    <li><%= link_to "Create New Card", '#', type:"button", 'data-toggle' => "modal", 'data-target' => "#cardModal" %></li>
				  </ul>
				</div>
			</div>
			<div class="col-md-12 col-sm-12 col-xs-12">
				<hr>
				<% if @cards.length != 0 %>
					<div class="col-md-12 col-sm-12 col-sm-12">
						<p style="padding-top:5px;"></p>
						<% @cards.each do |f| %>
							<% unless f.id.nil? %>
							<div class="deck-content col-md-12 col-xs-12 col-sm-12">
								<%= link_to truncate(f.front, length: 35), card_path(f.id), class:'pull-left' %>
								<div class="btn-group pull-right hidden-sm hidden-xs">
									<%= link_to "Delete Card", card_path(f.id), method: :delete, class: "btn btn-danger btn-sm" %>
								</div>
							</div>
							<% end %>
						<% end %>
					</div>
				<% else %>
					<p>No cards added yet!</p>
				<% end %>
				</div>
			</div>
			<p style="padding-bottom: 20px;"></p>
			<%= render 'shared/returnfooter' %>
		</div>
	</div>
</div>

<!-- Create Card Modal -->
<% provide :cardPurpose,'Create new Card' %>
<% provide :cardSubmit,'Create Card'  %>
<%= render 'shared/cardModal' %>

<!-- Share Deck Modal -->
<div id="shareDeck" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Share deck</h4>
      </div>
      <div class="modal-body">
		<%= form_for @deck do |f| %>
		<p>Once you choose to share your deck, it cannot be stopped. Click share to continue.</p>
		<div class="form-group">
			<%= f.hidden_field :share, class:"form-control", placeholder: 'Title of the Deck', value: true %>
		</div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Share", class: "btn btn-success pull-right" %>
        <% end %>
        <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">Cancel</button>
      </div>

    </div>

  </div>
</div>

<!-- Edit deck -->
<% provide :modal_title, 'Edit title of deck' %>
<% provide :modal_submit, "Edit" %>
<%= render 'new_deck' %>

<!-- Delete deck -->
<% provide :delete_id, "deleteDeck" %>
<% provide :delete_path, deck_path(@deck) %>
<%= render 'shared/deletecontent' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>FC - Flashcards all day</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <%= link_to 'FC', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li <% if current_page?(root_path) %> class="active" <% end %>><%= link_to 'Home', root_path %></li>
        <li <% if current_page?(about_path) %> class="active" <% end %>><%= link_to 'About', about_path %></li>
        <li <% if current_page?(contact_path) %> class="active" <% end %>><%= link_to 'Contact', contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
        <li <% if current_page?(decks_path) %> class="active" <% end %>><%= link_to "Study", decks_path %></li>
        <li <% if current_page?(share_path) %> class="active" <% end %>><%= link_to "Shared Decks", share_path %></li>
        <li <% if current_page?(edit_user_registration_path) %> class="active" <% end %>><%= link_to "Profile", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path , method: 'delete'%></li>
        <% end %>
        <% unless signed_in?%>
        <li><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-user"></span> Sign up<% end %></li>
        <li><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-log-in"></span> Login<% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= render partial: "shared/flashmessages", flash: flash %> 

<%= yield %>

<footer class="footer">
	<div class="container">
		<div class="col-xs-6 col-sm-4 col-md-8">
      <ul class="list-unstyled">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-4">
        <div class="nav navbar-nav" style="padding-top: 30px;">
            <a class="btn btn-social-icon btn-google-plus" href="http://google.com/+"><i class="fa fa-google-plus"></i></a>
            <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i class="fa fa-facebook"></i></a>
            <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i class="fa fa-twitter"></i></a>
            <a class="btn btn-social-icon" href="mailto:test@example.com"><i class="fa fa-envelope-o"></i></a>
        </div>
    </div>
		<div class="col-md-12 col-xs-12 col-sm-12">
      <p class="text-center"><em>© Copyright 2015 FC</em></p>
    </div>
	</div>
</footer>

</body>
</html>

app/views/shared/_cardModal.html.erb
<!-- New Card Modal -->
<div id="cardModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= yield :cardPurpose %></h4>
      </div>
      <div class="modal-body">
		<%= form_for @card do |f| %>
			<div class="form-group">
				<%= f.label :Front %></p>
				<%= f.text_area :front, rows:5, class:"form-control", placeholder: 'Front of the card', required:true %>
			</div>
			<div class="form-group">
				<%= f.label :Back %></p>
				<%= f.text_area :back, rows: 5,class:"form-control", placeholder: 'Back of the card', required:true %>
			</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <%= f.submit yield(:cardSubmit), class: "btn btn-success pull-right" %>
      </div>
		<% end %>
    </div>

  </div>
</div>

app/views/shared/_deletecontent.erb
<!-- New Deck Modal -->
<div id="<%= yield(:delete_id) %>" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Confirm deletion</h4>
      </div>
      <div class="modal-body">
        <p>This action cannot be undone after deletion. Click continue to delete.</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Confirm Deletion', yield(:delete_path), method: :delete, class: "btn btn-danger pull-right" %>
        <button type="button" class="btn btn-info pull-right" data-dismiss="modal">Cancel</button>
      </div>
    </div>

  </div>
</div>

app/views/shared/_deletecontent.html.erb
<!-- New Deck Modal -->
<div id="<%= yield(:delete_id) %>" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Confirm deletion</h4>
      </div>
      <div class="modal-body">
        <p>This action cannot be undone after deletion. Click continue to delete.</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Confirm Deletion', yield(:delete_path), method: :delete, class: "btn btn-danger pull-right" %>
        <button type="button" class="btn btn-info pull-right" data-dismiss="modal">Cancel</button>
      </div>
    </div>

  </div>
</div>

app/views/shared/_flashmessages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= message %>
  </div>
<% end %>

app/views/shared/_returnfooter.html.erb
    <footer class="return">
      <%= link_to "Return", yield(:return_link), class:"btn btn-default" %>
    </footer>

app/views/static_pages/_jumbotron.html.erb
<div class="jumbotron">
	<div class="container">
		<div class="col-xs-12 col-sm-12 col-md-12">
			<h1>FC</h1>
			<p>A simple way to study whenever you want, wherever you want</p>
		</div>
	</div>
</div>

app/views/static_pages/about.html.erb
<%= render 'jumbotron' %>

<div class="container">
	<div class="row row-header">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<h1>About FC</h1>
			<p>This service is setup so you can setup a deck of flashcards and be able to take it on the go. FC is an extrmely
			easy way to just create the deck of flashcards that you want to use, and then look at it anywhere in the world(provided 
			you have internet!).Download and share your flashcards with friends and family and start learning today!</p>
		</div>
	</div>

	<div class="row row-content">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<h1>About us</h1>
			<p>FC was created by individuals who found flashcards to be helpful in their learning however, found it cumbersome
			to make and carry it around. With FC, individuals should be able to concentrate on their studies and have no excuses
			for not studying whereever they go.</p>
		</div>
	</div>
</div>